name: Packer Format and Validate

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3.1.0

      - name: Run Packer Format Check
        run: packer fmt -check packer/webapp.pkr.hcl

      - name: Run Packer Init
        run: packer init packer/webapp.pkr.hcl

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Packer Validate
        run: packer validate packer/webapp.pkr.hcl